version: '3.8'

services:
  db: # Nome do servi√ßo para o POSTGRESSQL
    image: postgres:latest
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: meu-adminer
    ports:
      - "8888:8080"
    depends_on:
      - db 

volumes:
  postgres_data:
